name = "family-bike-map"
main = "src/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[routes]]
pattern = "bike-map.fryanpan.com"
custom_domain = true

[[kv_namespaces]]
binding = "CLASSIFICATION_RULES"
id = "7245fe9209344518a731ee8569ea3fcc"
preview_id = "3ad0d31a965a45da89ad16c1ef655d0a"

[[d1_databases]]
binding = "ROUTE_LOGS"
database_name = "bike-route-logs"
database_id = "0ccee590-8fea-4bf3-954e-5f02edc50a61"

[observability]
enabled = true
